const std = @import("std");
const assert = std.debug.assert;
const Pipeline = @import("Pipeline.zig");
const Symlink = @import("Symlink.zig");
const PatchCDB = @import("PatchCDB.zig");
const ZMake = @This();

pub const BuildSystemType = enum {
    /// ./configure && make && make install
    autotools,
    /// TODO: to be implemented
    cmake,
    /// TODO: to be implemented
    makefile,

    fn check_todo(self: @This()) void {
        switch (self) {
            .autotools => {},
            .cmake => @panic("TODO: to be implemented"),
            .makefile => @panic("TODO: to be implemented"),
        }
    }
};

b: *std.Build,
name: []const u8,
build_system_type: BuildSystemType,
source_dir: std.Build.LazyPath,
target: std.Build.ResolvedTarget,
optimize: std.builtin.OptimizeMode,
lto: std.zig.LtoMode,
separate_sections: bool,
gc_sections: bool,
strip: bool,
run_autogen: bool,
install_prefix: []const u8,
nproc: usize,
use_bear: bool,
build_dir_symlink: ?[]const u8,
configure_args: std.ArrayList([]const u8) = .empty,

pub const CreateOptions = struct {
    build_system_type: BuildSystemType,
    source_dir: std.Build.LazyPath,
    target: ?std.Build.ResolvedTarget = null,
    optimize: std.builtin.OptimizeMode = .ReleaseFast,
    lto: std.zig.LtoMode = .none,
    /// -ffunction-sections -fdata-sections
    separate_sections: bool = true,
    /// -Wl,--gc-sections
    gc_sections: bool = true,
    /// null: based on the `optimize`
    strip: ?bool = null,
    /// run ./autogen.sh before ./configure ?
    run_autogen: bool = false,
    /// logic install directory
    install_prefix: []const u8 = "/usr",
    /// make -jN (default: number of CPUs)
    nproc: ?usize = null,
    /// use `bear -- make` to build
    use_bear: bool = false,
    /// create symlink pointing to the `build_dir`
    build_dir_symlink: ?[]const u8 = null,
};

pub fn create(b: *std.Build, name: []const u8, options: CreateOptions) *ZMake {
    options.build_system_type.check_todo();

    const self = b.allocator.create(ZMake) catch unreachable;
    self.* = .{
        .b = b,
        .name = b.dupe(name),
        .build_system_type = options.build_system_type,
        .source_dir = options.source_dir,
        .target = options.target orelse b.graph.host,
        .optimize = options.optimize,
        .lto = options.lto,
        .separate_sections = options.separate_sections,
        .gc_sections = options.gc_sections,
        .strip = options.strip orelse switch (options.optimize) {
            .Debug => false,
            .ReleaseSafe => false,
            .ReleaseSmall => true,
            .ReleaseFast => true,
        },
        .run_autogen = options.run_autogen,
        .install_prefix = b.dupe(options.install_prefix),
        .nproc = options.nproc orelse std.Thread.getCpuCount() catch 1,
        .use_bear = options.use_bear,
        .build_dir_symlink = if (options.build_dir_symlink) |str| b.dupe(str) else null,
    };
    return self;
}

pub fn add_configure_arg(self: *ZMake, arg: []const u8) void {
    assert(self.build_system_type == .autotools);

    const b = self.b;
    self.configure_args.append(b.allocator, b.dupe(arg)) catch unreachable;
}

/// return the path to the `build_out` directory
pub fn build(self: *ZMake) std.Build.LazyPath {
    self.build_system_type.check_todo();

    const b = self.b;
    const allocator = b.allocator;

    // build options
    const zig_exe = b.graph.zig_exe;
    const zig_target = self.target.result.zigTriple(allocator) catch unreachable; // arch-os-abi (with os.version and abi.version)
    const pure_target = self.target.result.linuxTriple(allocator) catch unreachable; // arch-os-abi
    const zig_mcpu = std.zig.serializeCpuAlloc(allocator, self.target.result.cpu) catch unreachable; // cpu_model+features-features
    const f_raw_optimize = switch (self.optimize) {
        .Debug => "-g3 -O0",
        .ReleaseSafe => "-g1 -O2",
        .ReleaseSmall => "-g0 -Os",
        .ReleaseFast => "-g0 -O3 -Xclang -O3",
    };
    const f_optimize = switch (self.lto) {
        .none => f_raw_optimize,
        .full => b.fmt("{s} -flto=full", .{f_raw_optimize}),
        .thin => b.fmt("{s} -flto=thin", .{f_raw_optimize}),
    };
    const f_separate_sections = if (self.separate_sections) "-ffunction-sections -fdata-sections" else "";
    const f_gc_sections = if (self.gc_sections) "-Wl,--gc-sections" else "";
    const f_strip = if (self.strip) "-Wl,-s" else "";

    var description_buf: std.ArrayList(u8) = .empty;
    defer description_buf.deinit(allocator);

    // description of the build (rebuild when changes occur)
    const base_description = b.fmt(
        \\# Generated by zmake
        \\magic: {d}
        \\zig_exe: {s}
        \\zig_target: {s}
        \\pure_target: {s}
        \\zig_mcpu: {s}
        \\optimize: {s}
        \\lto: {s}
        \\f_optimize: {s}
        \\f_separate_sections: {s}
        \\f_gc_sections: {s}
        \\f_strip: {s}
        \\build_system_type: {s}
        \\run_autogen: {any}
        \\install_prefix: {s}
        \\bear: {any}
        \\
    , .{
        1, // change this when the build logic changes
        zig_exe,
        zig_target,
        pure_target,
        zig_mcpu,
        @tagName(self.optimize),
        @tagName(self.lto),
        f_optimize,
        f_separate_sections,
        f_gc_sections,
        f_strip,
        @tagName(self.build_system_type),
        self.run_autogen,
        self.install_prefix,
        self.use_bear,
    });
    description_buf.appendSlice(allocator, base_description) catch unreachable;

    // the configure arguments also need to be included in the description
    for (self.configure_args.items, 0..) |arg, i| {
        const arg_description = b.fmt("configure_arg[{d}]: {s}\n", .{ i, arg });
        description_buf.appendSlice(allocator, arg_description) catch unreachable;
    }

    const description = description_buf.toOwnedSlice(allocator) catch unreachable;

    // copy the source dir to the build directory
    const wf = b.addWriteFiles();
    wf.step.name = self.get_step_name("copy source");
    const build_dir = wf.addCopyDirectory(self.source_dir, "", .{});
    _ = wf.add(".zmake_build.desc", description); // trigger rebuild if necessary

    var pipeline = Pipeline.init(b, .{ .cwd = build_dir });

    // autogen.sh
    if (self.run_autogen)
        _ = pipeline.add_command("./autogen.sh", .{ .name = self.get_step_name("./autogen.sh") });

    // configure
    const configure = pipeline.add_command("./configure", .{ .name = self.get_step_name("./configure") });
    configure.addArg(b.fmt("CC={s} cc -target {s} -mcpu={s}", .{ zig_exe, pure_target, zig_mcpu }));
    configure.addArg(b.fmt("CXX={s} c++ -target {s} -mcpu={s}", .{ zig_exe, pure_target, zig_mcpu }));
    configure.addArg(b.fmt("LD={s} cc -target {s} -mcpu={s}", .{ zig_exe, pure_target, zig_mcpu }));
    configure.addArg(b.fmt("AR={s} ar", .{zig_exe}));
    configure.addArg(b.fmt("RANLIB={s} ranlib", .{zig_exe}));
    configure.addArg(b.fmt("OBJCOPY={s} objcopy", .{zig_exe}));
    configure.addArg(b.fmt("CFLAGS={s} {s}", .{ f_optimize, f_separate_sections }));
    configure.addArg(b.fmt("CXXFLAGS={s} {s}", .{ f_optimize, f_separate_sections }));
    configure.addArg(b.fmt("LDFLAGS={s} {s} {s}", .{ f_optimize, f_gc_sections, f_strip }));
    configure.addArg(b.fmt("--host={s}", .{pure_target})); // must use the linux target
    configure.addArg(b.fmt("--prefix={s}", .{self.install_prefix})); // the logic install directory
    for (self.configure_args.items) |arg|
        configure.addArg(arg); // configure arguments passed by the user

    // make -j<N>
    if (self.use_bear) {
        const bear_yml = wf.add("bear.yml", b.fmt(
            \\schema: "4.1"
            \\compilers:
            \\  - path: {s}
            \\    as: clang
        , .{zig_exe}));

        const bear = pipeline.add_command("bear", .{ .name = self.get_step_name("bear make") });
        bear.addArg("-c");
        bear.addFileArg(bear_yml);
        bear.addArg("--");
        bear.addArg("make");
        bear.addArg(b.fmt("-j{d}", .{self.nproc}));

        const patch_cdb = PatchCDB.create(b, build_dir.path(b, "compile_commands.json"));
        pipeline.add_step(&patch_cdb.step);
    } else {
        const make = pipeline.add_command("make", .{ .name = self.get_step_name("make") });
        make.addArg(b.fmt("-j{d}", .{self.nproc}));
    }

    // create symlink pointing to the build dir
    if (self.build_dir_symlink) |symlink_filename| {
        const symlink = Symlink.create(b, symlink_filename, build_dir);
        symlink.step.dependOn(pipeline.get_last_step()); // do symlink after `make`
        b.getInstallStep().dependOn(&symlink.step); // reference it in the `install` step
    }

    // make install DESTDIR=build_out
    const make_install = pipeline.add_command("make", .{ .name = self.get_step_name("make install") });
    make_install.addArg("install");
    const out_dir = make_install.addPrefixedOutputDirectoryArg("DESTDIR=", "build_out");

    // $install_prefix/{include, lib, ...}
    const rel_path = if (self.install_prefix.len > 0 and self.install_prefix[0] == '/')
        self.install_prefix[1..]
    else
        self.install_prefix;

    const build_out = out_dir.path(b, rel_path);
    return build_out;
}

fn get_step_name(self: *ZMake, step_name: []const u8) []const u8 {
    const b = self.b;
    return b.fmt("zmake:{s} {s}", .{ self.name, step_name });
}
